name: Build and test (Yangtze)

on:
  push:
    branches:
      - 'release/yangtze/lcm'
    tags:
      - '*'
  pull_request:
    branches:
      - 'release/yangtze/lcm'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build the whole xs-toolstack
        run: bash tools/travis.sh
        env:
          OCAML_VERSION: 4.08
          OPAMWITHTEST: true
