name: Create release from tag

on:
  push:
    tags:
      - '6.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install opam
      run: sudo apt-get install -y opam

    - name: Collect licenses
      run: ./tools/print-licenses.sh > licenses.txt

    - name: Archive upstream libraries
      run: make archive

    - name: Create release ${{ github.ref_name }}
      run: |
        gh release create ${{ github.ref_name }} --repo ${{ github.repository }} --generate-notes \
           licenses.txt xs-opam-repo-${{ github.ref_name }}.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
